#ifndef _INCLUDES_H_
#define _INCLUDES_H_

#define	bk2461_dev

#include <string.h>
#include <stdio.h>
#include <intrins.h>
#include <ABSACC.H>
#include <stdarg.h>
#include <math.h>

#include "bk51mcu.h"
#include "bk2461.h"
#include "patches.h"
#include "driver_rf.h"
#include "driver_uart.h"
#include "driver_gpio.h"
#include "BLE_boardcast.h"
#endif

/***********************************************************
						end file
***********************************************************/
